bio_website/bio_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'bio_website.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

	url(r'^admin/', include(admin.site.urls)),
	url(r'^',include('data.urls',namespace="data")),


]

bio_website/data/urls.py
from django.conf.urls import patterns, url

from data import views

urlpatterns = patterns('',
    url(r'^$', views.mainpage, name='mainpage'),
	url(r'^database/',views.database,name='database'),
	url(r'^login/',views.login,name='login'),
	url(r'^user/',views.user,name='user'),
	url(r'^loginmid/',views.loginmid,name='loginmid'),
	url(r'^change-password/',views.change_password,name='change-password'),
	url(r'^logout/',views.logout,name='logout'),
	url(r'^usermanage/',views.usermanage,name='usermanage'),
	url(r'^fail/',views.fail,name='fail'),
	url(r'^change_password_mid/',views.change_password_mid,name='change_password_mid'),
	url(r'^addmid/',views.addmid,name='addmid'),
	url(r'^getdata/',views.getdata,name='getdata'),
	url(r'^delete/(?P<username>.+)',views.user_delete,name='user_delete'),
	url(r'^result/(?P<ID>.+)',views.result,name='result'),
	url(r'^input/',views.input,name='input'),
	url(r'^addtag/',views.addtag,name='addtag'),
	url(r'^success/',views.success,name='success'),
	url(r'^list/(?P<feature>.+)',views.list_all,name='list_all'),
	url(r'^ajax/',views.ajax,name='ajax'),
	url(r'^search_name/',views.search_name,name='search_name'),
	url(r'^search_feature/',views.search_feature,name='search_feature'),
	url(r'^data_delete/',views.data_delete,name='data_delete'),
	url(r'^tag_delete/',views.tag_delete,name='tag_delete'),


	
)

bio_website/data/models.py
from django.db import models
from django import forms
# Create your models here.

#数据的模型
class Tag(forms.Form):
	TagName = forms.CharField()
	FeatureName = forms.CharField()

	




class GeneData(models.Model):
	GeneStandardName = models.CharField(max_length=10)
	SystematicID = models.CharField(max_length=50,primary_key=True)
	Synonyms = models.CharField(max_length=50)
	Product = models.CharField(max_length=200)
	ProductSize = models.CharField(max_length=50)
	Pic_1 = models.ImageField()
	Pic_2 = models.ImageField()
	Pic_3 = models.ImageField()
	Pic_4 = models.ImageField()
	Pic_1text = models.CharField(max_length=50,default='Pic_1')
	Pic_2text = models.CharField(max_length=50,default='Pic_2')
	Pic_3text = models.CharField(max_length=50,default='Pic_3')
	Pic_4text = models.CharField(max_length=50,default='Pic_4')
	
	def __str__(self):
		return self.SystematicID



class GetGeneData(forms.Form):
	GeneStandardName = forms.CharField()
	SystematicID = forms.CharField()
	Synonyms = forms.CharField()
	Product = forms.CharField()
	ProductSize = forms.CharField()
	Pic_1 = forms.ImageField()
	Pic_2 = forms.ImageField()
	Pic_3 = forms.ImageField()
	Pic_4 = forms.ImageField()
	Pic_1text = forms.CharField()
	Pic_2text = forms.CharField()
	Pic_3text = forms.CharField()
	Pic_4text = forms.CharField()
	MitoFeature = forms.CharField()
	MicroFeature = forms.CharField()
	CellFeature = forms.CharField()

	def __str__(self):
		return self.SystematicID


class Mitochondria(models.Model):
	FeatureName = models.CharField(max_length=50,primary_key=True)
	SystematicIDs = models.ManyToManyField(GeneData)
	def __str__(self):
		return self.FeatureName

class Microtubule(models.Model):
	FeatureName = models.CharField(max_length=50,primary_key=True)
	SystematicIDs = models.ManyToManyField(GeneData)
	def __str__(self):
		return self.FeatureName

class Cell(models.Model):
	FeatureName = models.CharField(max_length=50,primary_key=True)
	SystematicIDs = models.ManyToManyField(GeneData) 	
	def __str__(self):
		return self.FeatureName

class login_f(forms.Form):
	username = forms.CharField()
	password = forms.CharField() 

class change_f(forms.Form):
	oldpassword=forms.CharField()
	newpassword=forms.CharField()

class add_f(forms.Form):
	username = forms.CharField()
	password = forms.CharField()

bio_website/data/views.py
from django.shortcuts import render
import json,csv,os
# Create your views here.
from django.http import HttpResponse
from data.models import *
from django import forms
from django.template import Context,loader
from django.contrib import auth
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


def Navi(request):
	
	if request.user.is_authenticated():
		if request.user.username=='root1':
			username=request.user.username
			context={'username':username,'tem_name':'data/root-tem.html'}
			
		else:
			username=request.user.username
			context={'username':username,'tem_name':'data/user-tem.html'}
			
	else:
		context = {'username':'','tem_name':'data/visitor-tem.html'}

	return context
	


def success(request):
	context = Navi(request)
	from_page = request.META.get('HTTP_REFERER', '/') 
	
	context['from_page'] = from_page
	return render(request,'data/success.html',context)

def database(request):
	context = Navi(request)
		
	return render(request,'data/database.html',context)

@login_required(login_url='/login')
def input(request):
	if request.method == 'POST':
		getgenedata = GetGeneData(request.POST,request.FILES)
		
		if getgenedata.is_valid():

			System_list = GeneData.objects.filter()
			if getgenedata.cleaned_data['SystematicID'] in list(map(lambda x:x.SystematicID,System_list)):
				return redirect('/fail')
			
			data = GeneData()

			data.GeneStandardName = getgenedata.cleaned_data['GeneStandardName']
			data.SystematicID = getgenedata.cleaned_data['SystematicID']
			data.Synonyms = getgenedata.cleaned_data['Synonyms']
			data.Product = getgenedata.cleaned_data['Product']
			data.ProductSize = getgenedata.cleaned_data['ProductSize']
			data.Pic_1 = getgenedata.cleaned_data['Pic_1']
			data.Pic_2 = getgenedata.cleaned_data['Pic_2']
			data.Pic_3 = getgenedata.cleaned_data['Pic_3']
			data.Pic_4 = getgenedata.cleaned_data['Pic_4']
			data.Pic_1text = getgenedata.cleaned_data['Pic_1text']
			data.Pic_2text = getgenedata.cleaned_data['Pic_2text']
			data.Pic_3text = getgenedata.cleaned_data['Pic_3text']
			data.Pic_4text = getgenedata.cleaned_data['Pic_4text']
			Mitolist = getgenedata.cleaned_data['MitoFeature']
			Microlist = getgenedata.cleaned_data['MicroFeature']
			Celllist = getgenedata.cleaned_data['CellFeature']

			data.save()

			mito_list = list(map(lambda x:x.FeatureName,Mitochondria.objects.all()))
			micro_list = list(map(lambda x:x.FeatureName,Microtubule.objects.all()))
			cell_list = list(map(lambda x:x.FeatureName,Cell.objects.all()))

			Mitolist = Mitolist.split(',')
			Mitolist.pop(0)
			Mitolist = list(set(Mitolist))
			for mito in Mitolist:  
				if mito in mito_list:
					MitoFeature = Mitochondria.objects.get(FeatureName=mito)
					MitoFeature.SystematicIDs.add(data)
				else:
					MitoFeature = Mitochondria()
					MitoFeature.FeatureName = mito
					MitoFeature.save()
					MitoFeature.SystematicIDs.add(data)

			Microlist = Microlist.split(',')
			Microlist.pop(0)
			Microlist = list(set(Microlist))
			for micro in Microlist:
				MicroFeature = Microtubule()
				MicroFeature.FeatureName = micro
				MicroFeature.save()
				MicroFeature.SystematicIDs.add(data)


			Celllist = Celllist.split(',')
			Celllist.pop(0)
			Celllist = list(set(Celllist))
			for cell in Celllist:
				
				CellFeature = Cell()
				CellFeature.FeatureName = cell
				CellFeature.save()
				CellFeature.SystematicIDs.add(data)
		
			return redirect('/success')
		else:
			return redirect('/fail')
	else:
		return redirect('/fail')

@login_required(login_url='/login')
def addtag(request):
	if request.method == "POST":
		tag = Tag(request.POST)
		if tag.is_valid():
			tagname = tag.cleaned_data["TagName"]
			featurename = tag.cleaned_data["FeatureName"]
			feature_list = eval("%s.objects.all()"%tagname)
			if featurename not in feature_list:
				newtag = eval("%s()"%tagname)
				newtag.FeatureName = featurename
				newtag.save()
				return redirect('/success')
	return redirect('/fail')


def result(request,ID):
	context = Navi(request)
	genedata = GeneData.objects.get(SystematicID=ID)
	feature_list_mito = genedata.mitochondria_set.all()
	feature_list_micro = genedata.microtubule_set.all()
	feature_list_cell = genedata.cell_set.all()
	
	context['GeneData'] = genedata
	context['feature_list_mito'] = feature_list_mito
	context['feature_list_micro'] = feature_list_micro
	context['feature_list_cell'] = feature_list_cell
	
	
	return render(request,'data/result.html',context)




def login(request):
	context = Navi(request)
	if not request.user.is_authenticated():
		return render(request,'data/login.html',context)
	else:
		return redirect('/')

def mainpage(request):
	context = Navi(request)
		
	return render(request,'data/mainpage.html',context)


def loginmid(request):
	if request.method == "POST":
		login_infor = login_f(request.POST)
		if login_infor.is_valid():
			username = login_infor.cleaned_data['username']
			password = login_infor.cleaned_data['password'] 
			user=auth.authenticate(username=username,password=password)
			if user is not None and user.is_active:
				
				auth.login(request, user)
				return redirect('/user')
			
	return redirect('/fail')

def fail(request):
	context = Navi(request)
	from_page = request.META.get('HTTP_REFERER', '/') 
	
	context['from_page'] = from_page
	return render(request,'data/fail.html',context)


@login_required(login_url='/login')
def user(request):
	context = Navi(request)	
	return render(request,'data/user.html',context)

@login_required(login_url='/login')
def logout(request):

	user=request.user
	auth.logout(request)
	return redirect('/')

@login_required(login_url='/login')
def change_password(request):
	context = Navi(request)
	return render(request,'data/change-password.html',context)

@login_required(login_url='/login')
def change_password_mid(request):
	if request.method == "POST":
		change_infor = change_f(request.POST)
		if change_infor.is_valid():
			oldpassword = change_infor.cleaned_data['oldpassword']
			newpassword = change_infor.cleaned_data['newpassword'] 
			username=request.user.username
			user=auth.authenticate(username=username,password=oldpassword)
			if user is not None and user.is_active:
				
				user.set_password(newpassword)
				return redirect('/')
			
				
				
	return redirect('/fail')
		

@login_required(login_url='/login')
def usermanage(request):
	context = Navi(request)
	username=request.user.username	
	if not username=='root1':
		return redirect('/fail')
	else:
		
		return render(request,'data/usermanage.html',context)

@login_required(login_url='/login')
def addmid(request):
	username=request.user.username
	if username=='root1':
			
		add_infor=add_f(request.POST)
		if add_infor.is_valid():
				username=add_infor.cleaned_data['username']
				password=add_infor.cleaned_data['password']
				user=User.objects.filter(username__exact=username)
				if not user:
					User.objects.create_user(username,'',password)
					
					return redirect('/usermanage')
	return redirect('/fail')

@login_required(login_url='/login')
def getdata(request):
		username=request.user.username
		if not username=='root1':
			return redirect('/fail')
		else:
			ulist=User.objects.filter() 
			response_data={"rows":[]}
			deletestr1='<form action="../delete/'
			deletestr2='"><input type="submit" class="btn btn-default" value="delete"></input></form>'
			for user in ulist:
				response_data["rows"].append({"name":user.username,"delete":deletestr1+user.username+deletestr2})
				
			
		return HttpResponse(json.dumps(response_data))

@login_required(login_url='/login')
def user_delete(request,username):
		user=request.user.username
		if not user=='root1':
			return redirect('/fail')
		else:
			user=User.objects.get(username=username) 
			user.delete()
			
			return redirect('/usermanage')

@login_required(login_url='/login')
def list_all(request,feature):
	if request.method == 'GET':
		all_list = eval("%s.objects.all()"%feature)
		ret_list = list(map(lambda x:x.FeatureName,all_list))
		return HttpResponse(json.dumps(ret_list))
	return redirect('/fail')

@login_required(login_url='/login')
def ajax(request):
	if request.method == 'GET':
		ID = request.GET['ID'].upper()
		GeneStandardName=''
		Synonyms='Name Description'
		Product=''
		ProductSize=''
		
		with open("./data/static/data/file/PeptideStats.tsv") as f_1:
			reader = csv.reader(f_1,delimiter='\t')
			for row in reader:
				if row[0]==ID:
					Ps_2=row[1]
					Ps_1=row[4]
		with open("./data/static/data/file/gene_association.pombase") as f_2:
			reader = csv.reader(filter(lambda row: row[0]!='!', f_2),delimiter='\t')
			for row in reader:
				if row[1]==ID:
					GeneStandardName=row[2]
					Product=row[9]
				
		Ps_1=Ps_1+'aa,'
		Ps_2 = '%.2f'%(float(Ps_2)/1000)+'kDa'	
		ProductSize=Ps_1+Ps_2
		data={\
		'GeneStandardName':GeneStandardName,\
		'Synonyms':'Name Description',\
		'Product':Product,\
		'ProductSize':ProductSize\
		}
		return HttpResponse(json.dumps(data))
	return redirect('/fail')

def search_name(request):
	if request.method == 'GET':
		search_list = []
		if not 'SystematicID' in request.GET.keys():
			GeneStandardName = request.GET['GeneStandardName']
			search_list =  GeneData.objects.filter(GeneStandardName__iregex = r'%s'%GeneStandardName)
		if not 'GeneStandardName' in request.GET.keys():
			SystematicID = request.GET['SystematicID']
			search_list = GeneData.objects.filter(SystematicID__iregex = r'%s'%SystematicID)

		context = Navi(request)
		context['search_list'] = search_list
		if search_list == []:
			return redirect('/fail')
		return render(request,'data/result_search.html',context)
	else:
		return redirect('/fail')

def search_feature(request):
	if request.method == 'GET':

		Mitolist = request.GET['MitoFeature']
		Microlist = request.GET['MicroFeature']
		Celllist = request.GET['CellFeature']

		Mitolist = Mitolist.split(',')
		Mitolist.pop(0)
		Mitolist = list(set(Mitolist))

bio_website/data/templates/data/database.html
{% load staticfiles %}
<!DOCTYPE html>
<html>


<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<link rel="stylesheet" href="{% static 'data/css/bootstrap.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'data/css/main.css' %}" type="text/css">
</head>

<body>
	<nav class="navbar navbar-default navbar-fixed-top " id="head">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'data:mainpage' %}">USTC_Lab</a>
            </div>

			<div>
        		<p class="navbar-text"><span class="glyphicon glyphicon-user"></span>{{username}}</p>
				
    		</div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'data:mainpage' %}">Home</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'data:database' %}">database</a>
                    </li>
					{% include tem_name %}
              
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

	<section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static 'data/img/1.png' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static 'data/img/2.png' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static 'data/img/3.png' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static 'data/img/2.png' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static 'data/img/3.png' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

	<section class="database_title">
        <div class="container text-center">
                <h2>Try our database:MitoBase!</h2>
				<p>MitoBase is a database that provides the morphology features of the mitochondria and microtubules in the deletion mutants of the model organism S.pombe in a genome-wide scale.</p>
        </div>

	</section>
	<section class="gene-section">
	<div class="container">
		<div class="col-lg-4 well">
		<h2 class="gene-h2">search by gene name</h2>
		<form action="{% url 'data:search_name' %}" method="GET">
  			<div class="form-group">
    			<label for="name">SystematicID</label>
    	   	    <input type="text" class="form-control" placeholder="SystematicID" id="s1" name="SystematicID"> 
      			
    
			</div>
			<div class="form-group">
    			<label for="name">GeneStandardName</label>
    			<input type="text" class="form-control" placeholder="GeneStandardName" id="g1" name="GeneStandardName">
				<span class="help-block">input a SystematicID or choose to input GeneStandardName.Regular Expression is ok too.</span>
  			</div>
			<div class="form-group">
				<input id="search_by_name" type="submit" class="btn btn-default" value="Search"></input>
			</div>

  			
		</form>
		</div>

		<div class="col-lg-4 well col-lg-offset-1">
		<h2 class="gene-h2">search by gene feature</h2>
		<form action="{% url 'data:search_feature' %}" method="GET">
  			<div class="form-group">
                <label for="name">Mitochondria</label>
                <select id="MitoFeature" class="form-control feature" name="MitoFeature">
                    
                    
                </select>
                <br>
                <button type='button' class='btn btn-default addtag'>add another option</button>
            </div>

        

            <div class="form-group">
                <label for="name">Microtubule</label>
                <select id="MicroFeature" class="form-control feature" name="MicroFeature"> 
                    
                    
                        
                    
                </select>
                <br>
                <button type='button' class='btn btn-default addtag'>add another option</button>
            </div>

        

            <div class="form-group">
                <label for="name">Cell</label>
                <select id="CellFeature" class="form-control feature" name="CellFeature">
                    
                    
                </select>
                <br>
                <button type='button' class='btn btn-default addtag'>add another option</button>
                <br>
                <span class="help-block">choose default to match all feature</span>
            </div>

            
            
            <div class="form-group">
                <input  id="data-post" type="submit" class="btn btn-default" value="search"></input>
            </div>
		</form>
		</div>
	</div>
	</section>


	
	
	<section id="contact">
        <div class="container" >
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center" >
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p class="suggestion">this website is developing</p>
                    <p class="suggestion">if you have some suggestion ,please contact us!</p>
                </div>
               
                <div class="col-lg-12 text-center" >
                    <span class="glyphicon glyphicon-envelope envelope"></span>
                    <p class="suggestion"><a href="mailto:your-email@your-domain.com">USTC_Lab@ustc.edu.cn</a></p>
                </div>
                
            </div>
        </div>
    </section>
	
	<!-- jQuery -->
    <script src="{% static 'data/js/jquery.js' %}"></script>
	
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'data/js/bootstrap.js' %}"></script>
	<script src="{% static 'data/js/main.js' %}"></script>
	
</body>

bio_website/data/templates/data/usermanage.html
{% load staticfiles %}
<!DOCTYPE html>
<html>


<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<link rel="stylesheet" href="{% static 'data/css/bootstrap.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'data/css/main.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'data/css/bootstrap-table.css' %}" type="text/css">
</head>

<body>
	<nav class="navbar navbar-default navbar-fixed-top " id="head">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'data:mainpage' %}">USTC_Lab</a>
            </div>

			<div>
        		<p class="navbar-text"><span class="glyphicon glyphicon-user"></span>{{username}}</p>
				
    		</div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'data:mainpage' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'data:database' %}">database</a>
                    </li>
					{% include tem_name %}
              
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
	<section class="user_title">
        <div class="container text-center">
                <h2>user manage</h2>
        </div>

	</section>

	<section class="user-section">
		<div class="container">
		<div class="col-lg-8 col-lg-offset-2 well">
		
		<table id="AList" data-side-pagination="server" data-url="../getdata"></table>
		</div>
		</div>
	</section>
	<section class="database_title">
        <div class="container text-center">
				<h2>add new user</h2>
        </div>

	</section>
	<section class="user-section">
		<div class="container">
		<div class="col-lg-4 col-lg-offset-4 well">
		<h2 class="gene-h2">add-new-user</h2>
		<form action="{% url 'data:addmid' %}" method="POST">
  			<div class="form-group">
    			<label for="name">username</label>
				{% csrf_token %}
    			{{ form }}
    			<input type="text" class="form-control" placeholder="username" name="username">
			</div>
			<div class="form-group">
    			<label for="name">password</label>
    			<input type="password" class="form-control" placeholder="password" name="password">
				
  			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-default" value="add"></input>
			</div>

  			
		</form>
		</div>
		</div>
	</section>
    <section class="database_title">
        <div class="container text-center">
                <h2>delete-data</h2>
        </div>

    </section>
    <section class="user-section">
        <div class="container">
        <div class="col-lg-4 col-lg-offset-4 well">
        <h2 class="gene-h2">delete-data</h2>
        <form action="{% url 'data:data_delete' %}" method="GET">
            <div class="form-group">
                <label for="name">SystematicID</label>
                {% csrf_token %}
                {{ form }}
                <input type="text" class="form-control" placeholder="SystematicID" name="SystematicID">
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="delete"></input>
            </div>

            
        </form>
        </div>
        </div>
    </section>
    <section class="database_title">
        <div class="container text-center">
                <h2>delete-tag</h2>
        </div>

    </section>
    <section class="user-section">
        <div class="container">
        <div class="col-lg-4 col-lg-offset-4 well">
        <h2 class="gene-h2">delete-tag</h2>
        <form action="{% url 'data:tag_delete' %}" method="GET">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">add new tag</label>
                <select id="tagselect" class="form-control" name="TagName">
                    <option>Mitochondria</option>
                    <option>Microtubule</option>
                    <option>Cell</option>
                </select>
            </div>
            <div class="form-group hcontrol">
                <label for="name">Mitochondria</label>
                <select id="MitoFeature" class="form-control feature" name="Mitochondria">
                    
                    
                </select>
            </div>

        

            <div class="form-group  hidden hcontrol">
                <label for="name">Microtubule</label>
                <select id="MicroFeature" class="form-control feature" name="Microtubule"> 
                    
                </select>
            </div>

        

            <div class="form-group  hidden hcontrol">
                <label for="name">Cell</label>
                <select id="CellFeature" class="form-control feature" name="Cell">
                    
                    
                </select>
            </div>

            
            <div class="form-group">
                <input type='submit' class='btn btn-default' value="delete"></input>
            </div>

            
        </form>
        </div>
        </div>
    </section>
	<section id="contact">
        <div class="container" >
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center" >
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p class="suggestion">this website is developing</p>
                    <p class="suggestion">if you have some suggestion ,please contact us!</p>
                </div>
               
                <div class="col-lg-12 text-center" >
                    <span class="glyphicon glyphicon-envelope envelope"></span>
                    <p class="suggestion"><a href="mailto:your-email@your-domain.com">USTC_Lab@ustc.edu.cn</a></p>
                </div>
                
            </div>
        </div>
    </section>

	


	<!-- jQuery -->
    <script src="{% static 'data/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'data/js/bootstrap.js' %}"></script>

	<script src="{% static 'data/js/bootstrap-table.js' %}"></script>
	<script src="{% static 'data/js/main.js' %}"></script>
    
	<script type="text/javascript">
        $(document).ready(function(){
    

            $("#usermanage").addClass("active");
            $("#manage").addClass("active");
            $("#tagselect").change(function(){
                var name = $(this).val();
                $(".hcontrol").addClass("hidden");
                $("[name ="+name+"]").parent().removeClass("hidden");
            })

            $("body").on("click",".feature",function()
            {
                var cur = $(this);
                $.ajax(
                {
                    url:"/list/"+cur.prevAll("label:first").html(),    
                
                    type:'GET',           
                    success:function(arg)
                    {   
                        var obj=jQuery.parseJSON(arg);  
                        var length=obj.length;
                        var feature = "";
                        if (length>0)
                        {
                            for(var i=0;i<length;i++)
                            {
                                feature = feature + "<option>" + obj[i] + "</option>";
                            
                            }
                        }
                    
                        cur.html(feature);
                        cur.removeClass("feature");
                    
                    },
                    
                }); 
            }); 



        });
    </script>

</body>

bio_website/data/templates/data/visitor-tem.html
<li id="login">
	<a href="{% url 'data:login' %}">login</a>
</li>